---
name: "Zilliqa build setup"
description: "Provides basic setup for container image building"
inputs:
  ecr_server_host:
    description: "Host name of ECR used for the repository"
    default: 338149388389.dkr.ecr.eu-central-1.amazonaws.com
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        ECR_SERVER_HOST: ${{ inputs.ecr_server_host }}
      run: |
        ./img-build-tools-library/.github/actions/setup/environment.py > /tmp/env
        cat /tmp/env
        cat /tmp/env >> $GITHUB_ENV
