---
name: "Zilliqa build setup"
description: "Provides basic setup for container image building"
inputs:
  acr_server_host:
    description: "Host name of ECR used for the repository"
    default: 1932.amazon.com
    required: false
runs:
  using: "composite"
  steps:
    - shell: bash
      env:
        ACR_SERVER_HOST: ${{ inputs.ecr_server_host }}
      run: |
        ./img-build-tools-library/.github/actions/setup/environment.py > /tmp/env
        cat /tmp/env
        cat /tmp/env >> $GITHUB_ENV
