---
name: "AWS authentication"
description: "Authentication to AWS"
runs:
  using: "composite"
  steps:
    - id: aws_auth
      shell: bash
      env:
        AWS_ACCOUNT_ID: "${{ secrets.AWS_ACCOUNT_ID_ENGINEERING_DEV }}"
        AWS_PROFILE: z-engineering-dev-cicd
        AWS_REGION: eu-central-1
      run: |
        mkdir -p $HOME/.aws
        echo "${{ secrets.HOME_AWS_CONFIG }}" > $HOME/.aws/config
        echo "${{ secrets.HOME_AWS_CONFIG }}" > $HOME/.aws/credentials
        aws sts assume-role \
          --role-arn arn:aws:iam::${AWS_ACCOUNT_ID}:role/MetricsGlobalCICD \
          --profile ${AWS_PROFILE} \
          --role-session-name=zilliqa \
          --query 'join(``, [`export `, `AWS_ACCESS_KEY_ID=`, \
          Credentials.AccessKeyId, ` ; export `, `AWS_SECRET_ACCESS_KEY=`, \
          Credentials.SecretAccessKey, `; export `, `AWS_SESSION_TOKEN=`, \
          Credentials.SessionToken])' \
          --output text > .env
